### ISSUE TITLE
DD_TAGS not able to be applied

### ISSUE THREAD

**Issue by tmetodie** [DataDog/serverless-plugin-datadog#439]
## Expected Behavior
When performing **sls deploy** expecting to see in AWS Lambda an environment variable DD_TAGS equal to "team:personal,git.commit.sha:\<some SHA\>

## Actual Behavior
The DD_TAGS is equal to "git.commit.sha:\<some SHA\>" only

## Steps to Reproduce the Problem

  1. Serverless YAML
  ```
custom:
  datadog_lambda_extension_version: "49"
  datadog_lambda_extension_layer_arn: arn:aws:lambda:${self:custom.envRegion}:464622532012:layer:Datadog-Extension-ARM:${self:custom.datadog_lambda_extension_version}
  datadog_secret: <some API key>
<snip>
datadog:
    apiKey: ${self:custom.datadog_secret.api_key}
    enableTags: true
    tags: team:personal
<snip>
functions:
  service:
    handler: ./cmd/server-lambda/
    layers:
      - ${self:custom.datadog_lambda_extension_layer_arn}
    name: ${self:service}-service
    environment:
      <snip>
      DD_SERVICE: ${self:service}
      DD_ENV: ${self:custom.envName}-${self:custom.envRegion}
      DD_VERSION: ${self:custom.gitHash}
      DD_TAGS: team:personal
  ```

  2. Tried also with DD_TAGS=team:personal sls deploy but the variables are not considered and Lambda function does not change.

## Specifications

  - Serverless Framework version: 3.24.1
  - Datadog Serverless Plugin version:  4.3.0
  - Lambda function runtime (Python 3.7, Node 10, etc.): Custom runtime on Amazon Linux 2
  
## Stacktrace
  
  ```
  Paste here
  ```

**Comment by IvanTopolcic** [comment]
I believe was fixed [here](https://github.com/DataDog/serverless-plugin-datadog/pull/288), but you're using a 2 year old version of the plugin. Do you think you could upgrade and try again?

**Comment by tmetodie** [comment]
@IvanTopolcic , can you tell me which is the first version that has this change. I tried up to 5.14 (because we still run node v12) but I think it is still not working?

**Comment by astuyve** [comment]
Hi @tmetodie - node12 is in [phase 2 deprecation](https://docs.aws.amazon.com/lambda/latest/dg/lambda-runtimes.html) so you can no longer update those functions, you may need to update to a newer version of node and try again.

**Comment by astuyve** [comment]
re-closing this as per the last comment
